const itemsArr = [
  {itemText: "I'm aware of my strengths and weaknesses as a student.", reverseScore: false},
  {itemText: "I feel a sense of control over my academic performance.", reverseScore: false},
  {itemText: "It's important for me to understand how I learn.", reverseScore: false},
  {itemText: "When I finish a reading, I take time to review what I've learned.", reverseScore: false},
  {itemText: "I review my notes after class.", reverseScore: false},
  {itemText: "I connect material I'm studying to things I already know.", reverseScore: false},
  {itemText: "I'm comfortable with public speaking.", reverseScore: false},
  {itemText: "I'm confident in my ability to decide among several career options.", reverseScore: false},
  {itemText: "My grades are a reflection of my effort.", reverseScore: false},
  {itemText: "I have preferences when it comes to thinking about and organizing information.", reverseScore: false},
  {itemText: "I often complete assignments at the last minute.", reverseScore: true},
  {itemText: "Reading will be an important part of my future career.", reverseScore: false},
  {itemText: "I make sure I know what material will be covered on tests.", reverseScore: false},
  {itemText: "I make friends easily.", reverseScore: false},
  {itemText: "I have a regular sleep schedule.", reverseScore: false},
  {itemText: "I know how to gather information about possible careers.", reverseScore: false},
  {itemText: "I'm in control of my future.", reverseScore: false},
  {itemText: "My notes are legible and well organized.", reverseScore: false},
  {itemText: "I'm confident that I can identify the most important information to study.", reverseScore: false},
  {itemText: "I believe that I can develop the skills to be an effective writer.", reverseScore: false},
  {itemText: "Declaring my college major makes me anxious.", reverseScore: true},
  {itemText: "I haven't thought much about my learning preferences.", reverseScore: true},
  {itemText: "It's hard to find time to focus on homework.", reverseScore: true},
  {itemText: "I'm aware of several different note-taking styles.", reverseScore: false},
  {itemText: "I use several approaches to preparing for my tests.", reverseScore: false},
  {itemText: "I organize my thoughts and make a plan before beginning a writing assignment.", reverseScore: false},
  {itemText: "I'm a healthy person.", reverseScore: false},
  {itemText: "I find a sense of accomplishment to be very rewarding.", reverseScore: false},
  {itemText: "The same strategies I use to learn material in class will be helpful in my career.", reverseScore: false},
  {itemText: "I use my time well.", reverseScore: false},
  {itemText: "I can tell which information my instructors consider important.", reverseScore: false},
  {itemText: "I make an effort to develop relationships with my instructors.", reverseScore: false},
  {itemText: "I know how to develop healthy relationships.", reverseScore: false},
  {itemText: "I have a clear plan for completing my degree on time.", reverseScore: false},
  {itemText: "When I have a large project to complete, I start by making a plan.", reverseScore: false},
  {itemText: "I'm confident that I understand how to learn new material.", reverseScore: false},
  {itemText: "I can identify the most important points in my readings.", reverseScore: false},
  {itemText: "I always take notes in class.", reverseScore: false},
  {itemText: "I schedule my study time in the same way that I schedule work and class.", reverseScore: false},
  {itemText: "I view tests as a chance to demonstrate my knowledge.", reverseScore: false},
  {itemText: "I welcome the challenge of working on group assignments.", reverseScore: false},
  {itemText: "I eat three well-balanced meals each day.", reverseScore: false},
  {itemText: "I gather information from multiple sources before making a decision.", reverseScore: false},
  {itemText: "My grades are my responsibility.", reverseScore: false},
  {itemText: "I've never thought about my approach to studying.", reverseScore: true},
  {itemText: "I don't manage my time as well as I could.", reverseScore: true},
  {itemText: "I use different reading strategies for different classes.", reverseScore: false},
  {itemText: "I talk to my instructor before a test if there's something I don't understand.", reverseScore: false},
  {itemText: "I enjoy writing.", reverseScore: false},
  {itemText: "I find it easy to understand other people's feelings and motivations.", reverseScore: false},
  {itemText: "I have a clear understanding of my career interests.", reverseScore: false},
  {itemText: "I'm not sure why I learn better in some classes than in others.", reverseScore: true},
  {itemText: "I often find myself wondering where the time went.", reverseScore: false},
  {itemText: "When I come across a word I don't know, I almost always look it up.", reverseScore: false},
  {itemText: "I have a note-taking system that works for me.", reverseScore: false},
  {itemText: "When I make plans to study, I stick with them in spite of distractions.", reverseScore: false},
  {itemText: "I'm someone who gets involved in campus activities.", reverseScore: false},
  {itemText: "I exercise regularly.", reverseScore: false},
  {itemText: "Sometimes I worry about my ability to select the right college major.", reverseScore: true},
  {itemText: "I have both short-term and long-term goals.", reverseScore: false},
  {itemText: "I give up easily when I encounter trouble with an assignment.", reverseScore: false},
  {itemText: "I'm aware of how I learn best.", reverseScore: false},
  {itemText: "I frequently get distracted when I should be studying.", reverseScore: true},
  {itemText: "I acquired note-taking skills in high school, in previous college classes, or on the job.", reverseScore: false},
  {itemText: "I understand how memory works.", reverseScore: false},
  {itemText: "I have strategies to manage my anxiety before an exam.", reverseScore: false},
  {itemText: "I'm an active participant in class discussions.", reverseScore: false},
  {itemText: "I'm aware of many resources available to help pay for college.", reverseScore: false},
  {itemText: "Other people would describe me as goal directed.", reverseScore: false},
  {itemText: "Once I start something, I see it through to the end even if there are obstacles.", reverseScore: false},
  {itemText: "Procrastination sometimes gets in the way of my success.", reverseScore: true},
  {itemText: "I'm confident in my reading skills.", reverseScore: false},
  {itemText: "After a test, I evaluate the outcome and adjust my study approach as needed.", reverseScore: false},
  {itemText: "I know how to develop an effective presentation.", reverseScore: false},
  {itemText: "I'm comfortable sharing my thoughts and advocating for myself.", reverseScore: false},
  {itemText: "I'm worried about registering for the right classes next term.", reverseScore: true},
  {itemText: "I evaluate how much progress I've made toward achieving my goals.", reverseScore: false},
  {itemText: "I find myself looking for excuses not to study.", reverseScore: true},
  {itemText: "I adapt my learning style to meet the demands of the situation.", reverseScore: false},
  {itemText: "I actively think about the main idea of each paragraph as I read.", reverseScore: false},
  {itemText: "I study in short increments of time throughout the week.", reverseScore: false},
  {itemText: "The strategies I use to perform well on exams can help me in my current or future career.", reverseScore: false},
  {itemText: "I'm aware of the writing resources available at my school.", reverseScore: false},
  {itemText: "When speaking with someone, I'm aware of what my body language is communicating.", reverseScore: false},
  {itemText: "I manage stress well.", reverseScore: false}
]

export default itemsArr;